# Generated by Django 3.2.7 on 2021-09-24 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subID', models.CharField(max_length=500)),
                ('tkn', models.BigIntegerField()),
                ('pri', models.CharField(max_length=500)),
                ('dev', models.CharField(max_length=500)),
                ('evt', models.CharField(max_length=500)),
                ('time', models.DateTimeField(max_length=500)),
                ('mac', models.CharField(max_length=500)),
                ('thing', models.CharField(max_length=500)),
                ('devName', models.CharField(max_length=500)),
                ('aID', models.SmallIntegerField()),
                ('rID', models.SmallIntegerField()),
                ('rssi', models.SmallIntegerField()),
                ('txP', models.SmallIntegerField()),
                ('bat', models.SmallIntegerField()),
                ('scnTime', models.DateTimeField(default=datetime.datetime.now, max_length=500)),
                ('scnCnt', models.SmallIntegerField()),
                ('mov', models.SmallIntegerField()),
                ('temp', models.SmallIntegerField()),
                ('hmd', models.SmallIntegerField()),
                ('pres', models.BigIntegerField()),
                ('io1', models.SmallIntegerField()),
                ('io2', models.SmallIntegerField()),
                ('Icn', models.CharField(max_length=500)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
